### PR TITLE
Update lesson_07_project_prep.md

### PR DESCRIPTION
**Pull request by jpbatz**
git merge requires branch name: git merge mybranch

### CODE REVIEW

**Comment by seawolf42** [comment]
Please note that we are performing a *major* overhaul on all the lessons. This includes literally ripping all the content out of each file and moving it into an entirely new structure. We will not be accepting pull requests on master until that's done, and PRs made now will all become irrelevant. Can you instead make these same changes on the new files in the overhaul branch?

**Comment by chalmerlowe** [comment]
@jpbatz thanks for suggesting this. we appreciate it. as @seawolf42 mentioned, we spent all day yesterday working on the overhaul branch which will eventually replace, wholesale, all content on the master branch. If you find that this item propagates to the new content on overhaul branch, please let us know via a pull request.

**Comment by chalmerlowe** [comment]
@jpbatz thanks for suggesting this. we appreciate it. as @seawolf42 mentioned, we spent all day yesterday working on the overhaul branch which will eventually replace, wholesale, all content on the master branch. If you find that this item propagates to the new content on overhaul branch, please let us know via a pull request.

**Comment by seawolf42** [comment]
@jpbatz not sure if this still needs to be fixed after the overhaul, if you check, update, and re-submit the PR I will accept.

**Pull request closed without merging**
