### PR TITLE
Add sprint definition to README

### PR DESCRIPTION
**Pull request by DLance96**

### CODE REVIEW

**Comment by DLance96** [comment]
@jfmario How does this look based off your suggestion?

**Comment by jfmario** [comment]
Can't see it until @chalmerlowe approves the merge, but I'll keep an eye for it and give feedback.

**Comment by DLance96** [comment]
@jfmario If you go into files changed there is a view button in the top right which allows you to see the rendered markdown

**Comment by jfmario** [comment]
@DLance96 Ah didn't know you could do that. Looks legit @chalmerlowe

**Pull request merged**
