### PR TITLE
Issue #131 fix

### PR DESCRIPTION
**Pull request by Alestainer**

### CODE REVIEW

**Comment by seawolf42** [comment]
@Alestainer, you've got merge conflicts in this pull request. Can you fetch from this fork, pull to your master, and then merge your master into your branch and re-push?

**Comment by Alestainer** [comment]
@seawolf42 I did it and when I was resolving conflicts I realized that my fix is the only conflict.

**Comment by seawolf42** [comment]
@Alestainer while that may be the only conflict, as a maintainer I'm not sure how to disambiguate it. Can you fix the conflict on your branch and re-push so the PR includes the de-conflicted version?

**Comment by Alestainer** [comment]
@seawolf42 I'm not sure, but I think it's done.

**Comment by seawolf42** [comment]
Awesome, thanks @Alestainer!

**Pull request merged**
